# Generated by Django 3.2.7 on 2021-10-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='music',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
