# Generated by Django 3.2.7 on 2021-10-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_playlist', '0002_auto_20211005_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_playlist.artist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_playlist.music'),
        ),
    ]
